name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Azure Web App details
        id: webapp
        run: |
          echo "::set-output name=app-name::${{ secrets.AZURE_WEBAPP_NAME }}"
          echo "::set-output name=publish-profile::${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}"

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.webapp.outputs.app-name }}
          publish-profile: ${{ steps.webapp.outputs.publish-profile }}
          package: '.'
